# Generated by Django 4.1.2 on 2022-10-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_profile_photo_remove_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follows',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CREATOR', 'CREATOR'), ('SUBSCRIBER', 'SUBSCRIBER')], default='SUBSCRIBER', max_length=30),
        ),
    ]
