# Generated by Django 4.1.2 on 2022-10-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litr', '0003_ticket_time_created_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
